### PR TITLE
Add more definitions to bitcointx.core.secp256k1

### PR DESCRIPTION
**Pull request by romanz**
* secp256k1_pedersen_verify_tally
* secp256k1_rangeproof_verify
* secp256k1_surjectionproof_parse

### CODE REVIEW

**Comment by dgpv** [comment]
Generally, I add definitions for C functions only if they are used by python code, that means that their invocations will be likely to covered by tests.

If you want to use the functions directly in your code, you can add the definitions there - just do from `bitcointx.core.secp256k1 import secp256k1` and use it.

I am currently doing the refactoring of the code that would result in some API breakage for python-bitcointx (#20), and thus there will be new major version release. The elements code will go into separate package, python-elementstx. And pyhton-elementstx will do the same thing,

```
from bitcointx.core.secp256k1 import (
    secp256k1,
    SECP256K1_CONTEXT_SIGN, SECP256K1_CONTEXT_VERIFY,
    set_error_callback, randomize_context
)
```

and will set its types as needed.

**Comment by dgpv** [comment]
But also please note that this is a direct C interface via ctypes.

You are on your own to ensure that the functions are used correctly. To use this, you better have experience writing C code and understand all the internal workings.

**Comment by dgpv** [comment]
I added the change (https://github.com/Simplexum/python-bitcointx/commit/323009e533e869e8a821441f239affeb047ed254) that requires you to state that you know what you are doing when requesting the ctypes handle for secp256k1.

`secp256k1 = get_secp256k1_handle(I_REALLY_KNOW_C_AND_CTYPES=True)`

**Comment by dgpv** [comment]
After the refactoring that I am working on is complete, Elements code will go to separate module, python-elementstx, and this module, as well as other code where authors are confident in programming in C and using ctypes, will be able to use get their own handle to the ctypes module via function like this:

```
def load_secp256k1_library():
    """load libsecp256k1 via ctypes, add default function definitions
    to the library handle, and return this handle.
    Callers of this function must assume responsibility for correct usage
    of the underlying C library.
    ctypes is a low-level foreign function interface, and using the underlying
    library though it should be done with the same care as if you would be
    programming in C directly."""

    handle = ctypes.cdll.LoadLibrary(ctypes.util.find_library('secp256k1'))
    _add_function_definitions(handle)
    return handle
```

**Comment by dgpv** [comment]
The confidential_transactions branch is not planned to be progressed further, because all the Elements code will go to separate `python-elementstx` module.

I therefore close this PR.

**Comment by romanz** [comment]
Sounds good, thanks!

**Pull request closed without merging**
