### PR TITLE
Replace hashlib.ripemd160 with python-only implemenation

### LINKED ISSUE #64: Potential problem with RIPEMD160 removal from newer OpenSSL versions by default
See https://github.com/bitcoin-core/HWI/issues/305 and https://github.com/openssl/openssl/issues/16994.

Bitcoin Core solved it by writing own pure Python RIPEMD160 implementation (see https://github.com/bitcoin/bitcoin/pull/23716), but it's meant to be used only for tests as it isn't constant time.

### PR DESCRIPTION
**Pull request by dgpv**
The implementation is taken from Bitcoin Core's test framework

Closes #64

### CODE REVIEW

**Comment by dgpv** [comment]
Should have added type annotations

**Comment by dgpv** [comment]
Added type annotations.

**Comment by dgpv** [comment]
The Core's implementation is described as "Test-only" in https://github.com/bitcoin/bitcoin/commit/68ca8677e039a60b9f51938987d784cb58a3c995

But here we would be using it in the 'body' of the library, not only in tests.

We already use code from Core's test framework, for example,  `bitcointx/segwit_addr.py`. But `bitcointx/segwit_addr.py` is described as 'Reference implementation'.

I wonder if it is OK to use the Core's test framework implementation of ripemd160. On one hand, it passes the tests and is quite simple. On the other hand, it is "Test only".

The code from Electrum (https://github.com/spesmilo/electrum/blob/0df05dd914c823acae1828cad3b20bdeb13150e9/electrum/ripemd.py) is more complex, and has comments like "parallel round 1", but I doubt that it is any faster, there's no automatic parallelization in python AFAIK, as it could be done by the C/C++ compiler that the original code seems to be written for. This code does not claim to be 'Test-only', though.

**Comment by kristapsk** [comment]
It's marked as test-only just because of not being constant time, see code review discussion. https://github.com/bitcoin/bitcoin/pull/23716/commits/ad3e9e1f214d739e098c6ebbd300da5df1026a44#r765393461

**Comment by dgpv** [comment]
In https://github.com/bitcoin/bitcoin/pull/23716#pullrequestreview-827151110, @sipa says that it is 'Test-only' because it is not constant-time.

So the question is, is it possible that someone will be using `bitcointx.core.serialize.Hash160` on some secret data ? We can make `ripemd160` module into `_ripemd160` to show the fact that it is not 'public', and the only public access to it will be through Hash160, or the `OP_RIPEMD160` in the script interpreter.

The data within `Hash160` is first hased with `hashlib.sha256`, so through non-constant-timedness, it could potentially leak timing information about the sha256 hash of the data. If the data is such that it is possible to bruteforce its sha256-hashed value, then the person that used `Hash160` for hashing secret data might have a problem.

I wonder if the implementation in Electrum is constant-time.

**Comment by dgpv** [comment]
Just in case, I've added another PR #67 which uses ripemd160 implementation taken from Electrum

**Comment by dgpv** [comment]
As a result of discussion in https://github.com/Simplexum/python-bitcointx/pull/67#issuecomment-989880518, I've moved the `ripemd160.py` module to `_ripemd160.py` to mark it "non-public", and added docstrings to warn about non-constant-timedness of the code (added the warning also to `sha256.py` which has python-only impl of sha256 that provides access to midstate)

**Comment by dgpv** [comment]
squashed to make it single commit

**Comment by dgpv** [comment]
Merged in https://github.com/Simplexum/python-bitcointx/commit/afac19cda15cfa086b68cb912527e7e5abb468c5

**Pull request closed without merging**
