### PR TITLE
Replace hashlib.ripemd160 with ripemd160 impl taken from Electrum

### PR DESCRIPTION
**Pull request by dgpv**
The same in essence as #65, but the ripemd160 implementation code is taken from Electrum, from https://github.com/spesmilo/electrum/blob/0df05dd914c823acae1828cad3b20bdeb13150e9/electrum/ripemd.py, slightly adapted, fixed formatting, added type annotations.

### CODE REVIEW

**Comment by dgpv** [comment]
The test code for ripemd160 is still from the Core's test framework.

**Comment by dgpv** [comment]
The changes to the original code (besides removing semicolons `;` and replacing the func `new()` with `ripemd160()` is in this commit  https://github.com/Simplexum/python-bitcointx/pull/67/commits/83e3d8edf726a8a3c72ebafcebe506cb304db321 for easier review.

**Comment by dgpv** [comment]
One strange thing in this implementation is that it seems to check for `sys.byteorder` and has raisen an error otherwise (see https://github.com/Simplexum/python-bitcointx/commit/83e3d8edf726a8a3c72ebafcebe506cb304db321#r61627773)

Why it was like that I don't know, maybe @spesmilo can advise.

I removed this check and also used `<16I` instead of `<16L` for `struct.unpack` in that code.

**Comment by sipa** [comment]
@dgpv It's implemented in Python, there is no way to guarantee anything is constant time. But specifically, it uses modulo operations and integers of variable length.

**Comment by dgpv** [comment]
So, is making the `ripemd160` module internal (renaming to `_ripemd160`) and adding a warning in docstrings with the meaning 'do not use these hash funcs for secret data' seem to be appropriate measures ?

It does to me, considering the fact that adding a constant-time implementation would mean adding some dependency, which I would very much like to avoid.

**Comment by AdamISZ** [comment]
> So, is making the ripemd160 module internal (renaming to _ripemd160) and adding a warning in docstrings with the meaning 'do not use these hash funcs for secret data' seem to be appropriate measures ?

That was my thought (don't expose it; no one needs it exposed for normal Bitcoin usage), it's hardly likely that anyone would try to use the functionality for that purpose, but this would make it clear that they should not, in case it ever happened.

**Comment by dgpv** [comment]
Since this implementation cannot be constant-time, too, and is slightly slower than the one taken from Core's test framework (I've run python3 -m unittest bitcointx.tests.test_ripemd160 a few times to compare), I'm closing this PR, and #65 will be the active one.

**Pull request closed without merging**
